WIP Projects module
wearesideways/sw-site pull request #11
Opened 2022-11-24 22:13 UTC by markaar

2022-11-28 21:15 UTC, jaimeglez requested changes

2022-11-28 21:15 UTC, jaimeglez commented on src/components/OverflownHeadline.module.scss
> +@import '../style/lib';
Shouldn't you use OverflowHeadlineModule instead? you duplicated the code for this 🤔

2022-11-29 16:30 UTC, markaar commented on src/components/OverflownHeadline.module.scss
> +@import '../style/lib';
@jaimeglez that's because the `OverflowHeadlineModule` is wrapped in a section tag, my idea was to extract the headline only but I'm missing the refactor of that module

2022-11-29 16:59 UTC, jaimeglez commented on src/components/OverflownHeadline.module.scss
> +@import '../style/lib';
got it!

2022-11-29 17:20 UTC, jaimeglez requested changes

2022-11-29 17:20 UTC, jaimeglez commented on src/modules/ProjectsModule.tsx
> +  const [currentFilter, setFilter] = React.useState('All')
Use only `useState` and import on the first line `import React, { useState } from 'react'`, this applies for the next lines as well(`useId`)

2022-11-29 17:20 UTC, jaimeglez commented on src/modules/ProjectsModule.tsx
> +  function onClickFilter(e: React.MouseEvent, category: string) {
same comment as above

2022-11-29 17:20 UTC, jaimeglez commented on src/modules/ProjectsModule.tsx
> +  function filterButton(categoryLabel: string) {
This is basically another component(take a look to the `JobsModule.txs`, this component I'm guessing will accept `categoryLabel`, `onClick`(passing the onClickFilter) and `isSelected`... Making components and calling as functions makes a re-render issue.

2022-11-29 17:20 UTC, jaimeglez commented on src/modules/ProjectsModule.tsx
> +  const filtersContent = (
Similar as above, since this is returning jsx code this should be a separated component

2022-11-30 17:04 UTC, jaimeglez commented on src/modules/ProjectsModule.tsx
> +          {filteredProjects()?.map(({ project }, index) => {
Normally this is a bad practice due the re-rendering executing a function, this could be solved using a `useEffect` where you can watch the `currentFilter` and set the filteredProjects, maybe the code could be seen like this

```
  import React, { useEffect } from 'react'

  const [filteredProjects, setFilteredProjects] = useState(sortFilters)
  
  useEffect(() => {
    const fp = currentFilter === 'All'
      ? projectsList
      : projectsList.filter((el) => el.project.category === currentFilter)
    setFilteredProjects(fp)
  }, [currentFilter])
```

2022-11-30 19:58 UTC, merged