Added Centered Gallery
wearesideways/sw-site pull request #28
Opened 2023-03-17 23:22 UTC by Xaiid

2023-03-20 19:24 UTC, jaimeglez requested changes

2023-03-20 19:24 UTC, jaimeglez commented on src/modules/CenteredCarouselModule.tsx
> +                    sizes="FIXME"
use values for this attribute, in this case the image covers ~85% so you could use `sizes='85vw'` but since in mobile it changes, the right value will be `sizes='(min-width: 768px) 85vw, 100vw'`

2023-03-21 01:38 UTC, luishdz1010 requested changes

2023-03-21 01:38 UTC, luishdz1010 commented on src/modules/CenteredCarousel.module.scss
> +// TODO look for a cleaner solution, this is nested to override swiper pagination classes
@jaimeglez can you check the nesting? I think all of this can be done inside .root at the first level, thus not needing selector-max-compound-selectors disabled

2023-03-21 19:48 UTC, luishdz1010 approved these changes

2023-03-21 21:41 UTC, merged