Jg/text module
wearesideways/sw-site pull request #5
Opened 2022-10-14 22:51 UTC by jaimeglez

2022-10-18 16:58 UTC, jaimeglez commented
You can see the page of module catalog in [/module-catalog](https://e39e977a.sideways.pages.dev/module-catalog)

2022-10-18 17:17 UTC, luishdz1010 requested changes

2022-10-18 17:17 UTC, luishdz1010 commented on content/pages/module-catalog.mdx
> +    secondaryText: Sideways is a digital-first branding and creative agency uniquely positioned to differentiate your brand in a world where branding never stops.
How does the field work? I don't see any definition of text1-text4 anywhere. In other words, where are the ACFs?

2022-10-18 17:17 UTC, luishdz1010 commented on package.json
> +    "sass": "^1.55.0",
Not needed I believe (already on dev-deps)

2022-10-18 17:17 UTC, luishdz1010 commented on src/components/Text.tsx
> +      <style jsx>{`
Use scss file instead (also don't hardcode media queries)

2022-10-18 17:17 UTC, luishdz1010 commented on src/components/Text.tsx
> +    <div className={`text-module ${className ? className : ''}`}>
`className ?? ''`

2022-10-18 17:17 UTC, luishdz1010 commented on src/components/Text.tsx
> +export function Text({ primaryContent, divider, secondaryContent, cta, className }: Props) {
Text is too generic of a name, find a better, larger one

2022-10-18 17:17 UTC, luishdz1010 commented on src/modules/TextModule.tsx
> +export default function TextModule({
This name is better, but if you can find a better name that's also good (assuming we have other similar single-text modules elsewhere)

2022-10-18 17:17 UTC, luishdz1010 commented on src/modules/text.module.scss
> +
Remember to use the module mixin at the root of the component. Also, all modules need a root element of type `section` so we can use  ` :first/last-of-type` selectors for overriding spacing.

2022-10-18 17:17 UTC, luishdz1010 commented on src/style/lib/typography.scss
> +  font-weight: 100;
Is this font weight actually in the font files?

2022-10-20 17:02 UTC, jaimeglez commented on src/style/lib/typography.scss
> +  font-weight: 100;
my bad, that was to be intended 300, changing

2022-10-21 00:49 UTC, luishdz1010 approved these changes

2022-10-21 00:49 UTC, luishdz1010 commented on src/components/TextDividerText.tsx
> +  cta?: ReactNode
Can be merged with secondaryContent

2022-10-21 00:49 UTC, luishdz1010 commented on src/modules/HeadlineIntro.module.scss
> +  // @include make-container();
remove

2022-10-21 00:49 UTC, luishdz1010 commented on src/pages/[page].tsx
> +  console.log('data-->', data)
x

2022-10-21 00:49 UTC, luishdz1010 commented on src/components/TextDividerText.tsx
> +import styles from '../style/text-divider-text.module.scss'
This file should be co-located in the same folder as the component

2022-10-21 00:49 UTC, luishdz1010 commented on src/style/text-divider-text.module.scss
> +@import '../style/modules';
Not needed I think

2022-10-21 00:49 UTC, luishdz1010 commented on src/style/text-divider-text.module.scss
> +  }
Is this used? Seems weird to call it `module` when this is just a component

2022-10-21 00:49 UTC, luishdz1010 commented on content/pages/module-catalog.mdx
> +    text4: Modern Hospitality
Remove

2022-10-21 00:49 UTC, luishdz1010 commented on package.json
> +    "netlify-cms-proxy-server": "^1.3.24",
This is added twice

2022-10-21 00:49 UTC, luishdz1010 commented on src/modules/HeadlineIntroModule.tsx
> +              <span className={styles['line']} />
Here you can hardcode the strings that were on the yml. Or add then as default params of the function `text1 = 'lorem', text2 ='etc'`

2022-10-21 00:49 UTC, luishdz1010 commented on src/pages/[page].tsx
> +import { MDXRemoteSerializeResult } from 'next-mdx-remote/dist/types'
probably not a good idea to import from dist/types. check if the import is available the root of the pkg

2022-10-21 18:45 UTC, merged