Added animation to client headlines
wearesideways/sw-site pull request #50
Opened 2023-04-11 22:34 UTC by Xaiid

2023-04-11 23:03 UTC, jaimeglez commented
@luishdz1010 Zaida already finished this version, so we could let the Team know and they could decide what is the final decision, taking this or the things they mentioned(but creating a ticket for it)

2023-04-11 23:34 UTC, luishdz1010 commented on src/modules/ProjectsModule.tsx
> +                      <ParallaxProvider>
`ParallaxProvider` should not be rendered more than once per module

2023-04-13 18:29 UTC, luishdz1010 requested changes

2023-04-13 18:29 UTC, luishdz1010 commented on src/components/OverflownHeadline.tsx
> +export default function OverflownHeadlineWitParallax(props: Props) {
Doesn't seem like you are using this anywhere. Regardless, this solution doesn't work because you are still rendering many `ParallaxProvider` per module. Instead, render the Parallax provider at the root of the modules that may use the overflow headline in parallax mode.

2023-04-17 18:04 UTC, luishdz1010 approved these changes

2023-04-17 18:04 UTC, merged