Hero module WIP
wearesideways/sw-site pull request #6
Opened 2022-10-19 00:02 UTC by markaar

2022-10-31 17:21 UTC, jaimeglez requested changes

2022-10-31 17:21 UTC, jaimeglez commented on src/components/Media.tsx
> +        className={`${swmediaClasses.join(' ')} ${className ?? ''}`}
I'm using classNames package, I'm not sure if we should keep doing this with join or with the method classsNames? what do you think @luishdz1010 ?

2022-10-31 17:21 UTC, jaimeglez commented on src/components/Media.tsx
> +  mediaType: string
This could be a enum, in order to have specific types, example:
enum MediaTypes {
  Image,
  Video,
  ...
}

2022-10-31 17:21 UTC, jaimeglez commented on src/modules/HeroModule.tsx
> +  quoteText?: any[]
This is an array of strings, correct? this could be `string[]`

2022-10-31 17:21 UTC, jaimeglez commented on src/modules/HeroModule.tsx
> +          quoteText.length > 0 &&
you can simplify using the condition on the same line as `quoteText?.length &&` and removing the line 33

2022-10-31 17:46 UTC, jaimeglez commented on next.config.js
> +  },
is this working?

2022-10-31 18:34 UTC, luishdz1010 requested changes

2022-10-31 18:34 UTC, luishdz1010 commented on src/modules/HeroModule.tsx
> +          quoteText.length > 0 &&
In this particular case, because you have no `else` branch, you can just do` quoteTest?.map(...)`

2022-10-31 18:34 UTC, luishdz1010 commented on src/modules/HeroModule.tsx
> +          slides.map((slide, index) => (
slides?.map

2022-10-31 18:34 UTC, luishdz1010 commented on src/modules/HeroModule.tsx
> +      </button>
add aria-label=scroll down

2022-10-31 18:34 UTC, luishdz1010 commented on src/modules/Hero.module.scss
> +  }
put these clases at the top level, no need for nesting with css modules

2022-10-31 18:34 UTC, luishdz1010 commented on src/components/Media.module.scss
> +}
remove, not useful since it can't be imported and no effect in css modules

2022-11-01 22:56 UTC, markaar commented on src/modules/HeroModule.tsx
> +  quoteText?: any[]
@jaimeglez It's an array of objects

2022-11-10 00:19 UTC, markaar commented on next.config.js
> +  images: {
I put them inside assets but on a second thought I better move them to the images public folder

2022-11-10 00:41 UTC, markaar commented on src/modules/HeroModule.tsx
> +              <TextWithMixedFonts key={`quote-${index}`} {...elem.line} />
Not particularly but it could be refactored, the quotes followed a certain pattern so that's why I created the TextWithMixedFonts module

2022-11-11 16:58 UTC, markaar commented on next.config.js
> +  },
I forgot that is required to prevent this:


```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
--
10:36:54.622 | Possible solutions:
10:36:54.622 | - Use `next start` to run a server, which includes the Image Optimization API.
10:36:54.622 | - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
```

2022-11-12 00:38 UTC, markaar commented
@jaimeglez @luishdz1010  I'm leaving the media changes (video, etc) for another PR so this doesn't grow too much

2022-11-16 18:38 UTC, luishdz1010 requested changes

2022-11-16 18:38 UTC, luishdz1010 commented on src/modules/Hero.module.scss
> +  .media-figure {
don't nest CSS, is not necessary in CSS modules. It is only necessary when targeting child components, not for normal elements (h3.my-class)

2022-11-16 18:38 UTC, luishdz1010 commented on src/lib/types.ts
> +  MP4_URL = 'mp4',
We probably should only support MP4

2022-11-17 19:35 UTC, luishdz1010 approved these changes

2022-11-17 19:44 UTC, merged